### ISSUE TITLE
Reported Challenge #43339 - London - ML Crossing Detection

### ISSUE THREAD

**Issue by mvexel** [maproulette/challenge-reports#29]
Challenge: [#43339 - London - ML Crossing Detection](https://maproulette.org/browse/challenges/43339) 

 Reported by: [rskedgell](https://www.openstreetmap.org/user/rskedgell)

Almost every task "completed" in this challenge resulted in low quality edits which have taken time to fix - see Osmcha and changeset comments for changesets in London, GB tagged #MLCrossingDetection #MLCrossingDetection #maproulette.

Crossings have frequently been tagged incorrectly, or introduced unwanted iD-isms. Pointless decorative sidewalks with no routing connections were frequently added, which have had to be either connected or deleted.

While the ML Crossing Detection itself seemed to work quite well, this task was clearly unsuitable for the novice mappers who attempted it.

**Comment by atiannicelli** [comment]
[rskedgell](https://www.openstreetmap.org/user/rskedgell), I thank you for your work to complete this challenge! I am a bit confused as to why you reported the challenge after completing so many of the task successfully. I do understand that some of the edits that resulted from this challenge may have had some errors or were incomplete, and I thank you for flagging the issues and fixing the ones that you found. It seems rash to have flagged this challenge when the challenge simply helped people identify possible missing crossing ways and has seemed to do a good job at that. Are there changes to this challenge or the instructions that I could apply that would help to direct mappers to make better edits? 

As for the errors that mappers made while completing this challenge I saw a few that I will try to document here for completeness.
1) Added crossing node along a sidewalk that crosses over a pedestrian street. No need for crossing ways when the sidewalk doesn't cross a car navigable road. [rskedgel removed this crossing node](https://osmcha.org/changesets/149762799)
2) crossing markings set to "dots". [rskedgel changed the markings to "dashes"](https://osmcha.org/changesets/149765163)
3) "Decorative sidewalks". [rskedgel removed decorative sidewalks](https://osmcha.org/changesets/149764140)
4) sidewalk was mapped through a fence [rskedel added the fence and fixed the position of the sidewalk](https://osmcha.org/changesets/149763083)

Other edits that change the edits that were made due to this challenge that I see are adding more tags or small edits to clean up some geometries. It is always our goal to increase the completeness and accuracy of OSM and I feel that this challenge did work toward a more complete map. Although I regret the few added errors mappers made while working on this challenge I would invite suggestions as to what we can do to this challenge to make it a better challenge to prevent any such errors in the futre.

**Comment by Cj-Malone** [comment]
Pinging him on here might help @rskedgell

**Comment by CollinBeczak** [comment]
Closed as this is a stale report. Please message in this thread if you think the issue should be reopened.
